### ISSUE TITLE
Some bugs of the latest version, that I could find.

### ISSUE THREAD

**Issue by Havcom** [pa1nki113r/Project_Brutality#110]
First of all, tell me where exactly the best thing is to send a report so that the developer reacts faster? And that is, there is a discord and something else, I do not know)

**I will try to supplement the sheet from time to time, as long as it is relevant.**

**1** - Perhaps this is a trick, not a bug, but it looks funny. When the bodies hanging on the stake are destroyed by an explosion, they begin to rotate))
I think it should not be so.
Video - https://youtu.be/14F69Al1h_E

**2** - After a long shooting from a minigun, its trunk turns red. If at this moment throw a grenade, a mine, the player let down weapon, and the red trace of the weapon remains.
Screen - https://wampi.ru/image/6u4zQdf

**3** - When firing a rail gun in the aiming mode, I found that the ammo of her become infinite and even if I have 0 ammo in the mag, the weapon does not want to reload and continues to shoot.
The same does not apply to the second mode of microwave. there everything works correctly.

**4** - About two double-barreled shotgun already mentioned earlier. Holding two double-barrel shotguns in hands, when i try to cling to the ledge, the weapon animation breaks.

**5** - Finally, fix the invisible sprites for the grenade launcher, SMG, enhance the usual shotgun, which lie on the ground.

**6** - If you complete the level with a nailgun in your hands, at the start of a new level, he will start playing the animation of changing the shooting mode.
This looks normal for SMG, but not for nailgun.

**7** - When using the minigun with an improvement (triple barrel), pressing the right mouse button causes the trunks to spin. After that, if you change the weapon, the sound of the spining of the barrels will play for some time.

**8** - There is another thing that is incomprehensible to me. Why is another sight displayed in the sight of an assault rifle ??
Screen - https://wampi.ru/image/6u4vTG0

**9** - About the unloading of weapons:
- Not quite correct discharge animation for second rail gun shooting mode (microwave)
- Nailgun unloading does not work correctly
- Unloading improved automatic shotgun leads to a game crash (version GZdoom 3.6.0.0)

**10** - Choosing a chainsaw and throwing it out, the sound of the included chainsaw will continue to play until the player changes the weapon.

And the last, trifle, but it looks ugly. Some weapons are cropped at the bottom, some are not. I think the gap in the sprites or their wrong setting. Can this also be fixed?
https://wampi.ru/image/6u4Gcgn
https://wampi.ru/image/6u4GdEI
https://wampi.ru/image/6u4GxSJ
https://wampi.ru/image/6u4G6z4

**Comment by JMartinez9820** [comment]
The sprites being cropped from the bottom is a script issue, and not a sprite and offset issue. It has to do something the Weapon X/Y script being broken and making weapons looked cropped. Hopefully this will be fixed in the future. About the Dual SSG weapon animation being broken after clinging the edge, this happens after you cling the edge and then switching a weapon. This can be fixed by jumping again.

**Comment by Cacodemon345** [comment]
Bugs can take time to get fixed.

**Comment by Emircan34** [comment]
NO. 5 bug is happens me too. Because author is forgot to add sprites, but i fixed this bug so i guess it will be fixed soon.

**Comment by JMartinez9820** [comment]
About this issue:
1. Possibly vertices issues with the platforms
2. An oversight due to the red heat overlay
3. Oversight, will be fixed in the railgun's overhaul
4. Dual wield hasn't been overhauled yet. Pressing weapon special will fix this.
5. Resolved
6. Minor priority
7. Oversight probably due to sound calls
8. Brightmap error, fixed in #266 
9. Nailgun is fixed but the others are not. I did make a fix for the Autoshotgun in the Discord server
10. Oversight probably for sound reasons too

**Comment by scaryred24** [comment]
Unless this comes up again, consider this closed.
