### ISSUE TITLE
Boss Brain when killed does not end the level?

### ISSUE THREAD

**Issue by Nevermore2790** [pa1nki113r/Project_Brutality#115]
When the Boss Brain dies (Romero's Head), the map still continues instead of the level/map ending when it dies. Tested on Whispers of Satan, and happened when I entered MAP34 which ends on an Icon of Sin fight (Boss Brain).

**Comment by MekBoss** [comment]
Fault of some ACS script attached to some player action. Because it is an only thing that try to do something when level must ends. What exactly I dont know because I dont want to touch piece of code which almost removed in my local build. So just wait next PB release.

I strongly suspect that this is map fault because it using some tricks with player voodoo doll for map scripting, which acs script dont expect to happening.

**Comment by goldenmobster** [comment]
I tested it out and worked out just fine , This Bug no longer persists & therefore this issue is being closed
