### ISSUE TITLE
About of Bugs

### ISSUE THREAD

**Issue by Havcom** [pa1nki113r/Project_Brutality#130]
Hello. I gave myself a short break for several months, but I watched the development of the mod and what do I see now? I see that you have updated several types of weapons, which is undoubtedly wonderful, but no one fixes bugs, as I noticed, besides, after your updates, they become even bigger and I don’t quite understand what the developer or developers are doing? Maybe you postpone your innovations and start fixing bugs? And do not say that they do not interfere with play. From my last post about bugs there was almost nothing corrected.

Some errors, were described by me here, but they seem to be ignored.
https://github.com/pa1nki113r/Project_Brutality/issues/110

**Comment by JMartinez9820** [comment]
Hey Havcom, sorry if your bugs are getting ignored. The team is trying their hardest to eliminate most of the bugs they can. However, the team is currently focusing on the weapons overhaul so the bugs will be fixed later on. Bugs take time to fix bud.

**Comment by JMartinez9820** [comment]
If you have a Discord, you are welcome to join our [Discord] (https://discord.gg/2hJxXPc) server if you want.

Make sure to type ~>iam accepted in the verification channel.

**Comment by Cacodemon345** [comment]
> Maybe you postpone your innovations and start fixing bugs? And do not say that they do not interfere with play. From my last post about bugs there was almost nothing corrected.

Do note that the developers has a lot of IRL stuff to take care of apart from Project Brutality.

**Comment by Havcom** [comment]
JMartinez9820, Thanks for your reply. I understand everything, I myself once was engaged in the creation of mods, but for another game, but can you fix at least something old before adding something new? And to be engaged in testing before adding a new assembly?

**Comment by JMartinez9820** [comment]
Havcom, make sure to read Cacodemon345's message above. Some of the developers have life stuff to take care of first, so not all bugs will be fixed at the nick of time. Taking care is more important and should be taken care of first apart from Project Brutality.

**Comment by ADoomedSpaceMarine** [comment]
I actually really appreciate how real you are @JMartinez9820 I ended up getting a pull request to fix a couple that I personally noticed. Two of them were minor, shell ejection issues and the second was a game breaking glitch in the plasma rifle that caused the ZDoom console to crash before initializing the game. I have a wife and kid at home, and am juggling a full time software engineering degree so in that light I really respect your views. Thanks for all the hard work you guys put in. I was trying to figure out what was breaking the silenced pistol bug above this one. I will let you guys know if I make any progress. Is the discord available for me to join as well, in order to perhaps more effectively communicate with the development channels of this project?
