### ISSUE TITLE
First Aid Kit Broken/Portable Medkit [No work]

### ISSUE THREAD

**Issue by ghost** [pa1nki113r/Project_Brutality#145]
The First Aid Kit / Portable Medkit doesn't work at all 

![bandicam-2019-05-23-11-25-04-632](https://user-images.githubusercontent.com/33986489/58266139-13d31600-7d4f-11e9-9cf7-5ca0d40fbfd2.gif)

**Comment by tunbridgep** [comment]
The backpack can be used currently by activating it directly from the inventory. But that's a temporary workaround and is a real shame because you miss out on the cool animation.

I have completely fixed this issue, but this has gameplay implications. Currently it works like this:

- The backpack can't heal you above 100% Health
- Using the backpack from the inventory does nothing (I am going to change this to make it trigger the animation and heal like normal)
- Using the "heal" equipment item works perfectly and heals as expected.

There are currently no rules surrounding any maximum heal amounts. You can go from 1 HP to 100 in one go as long as you have enough charge. Depending on the needs of the mod, this could easily be changed to make it heal, say, a maximum of 50 HP. I'm sure everyone would like feedback on this.
