### ISSUE TITLE
Dual wielding

### ISSUE THREAD

**Issue by cacy17** [pa1nki113r/Project_Brutality#155]
Doesn't double ammo amount.

**Comment by goldenwarriorgw** [comment]
Can you provide more info please ?

**Comment by JMartinez9820** [comment]
@cacy17, please provide more info on what causes this issue when opening up an issue next time. Provide info on what causes it, how it can be replicated, etc. This is needed so the devs can be aware of the issue and can be fixed in a later revision. Failure to provide sufficient info can result in the bug not being fixed, and the devs won't even know what to do to fix it. So please, provide more info when reporting an issue next time.

**Comment by cacy17** [comment]
In brutal doom dual  weilding increases the clip capacity for that weapon. In this the ammo capacity stays the same

**Comment by goldenwarriorgw** [comment]
Yes, that is true , but this is PB _NOT_ BD

**Comment by JMartinez9820** [comment]
Fixed in latest commit.
