### ISSUE TITLE
Fatal Error in New Update

### ISSUE THREAD

**Issue by webursey** [pa1nki113r/Project_Brutality#188]
When launched through ZDL on GZDoom, the application won't launch, and this error comes up:

Execution could not continue.

Script error, "Project Brutality.zip:zscript.zc" line 1:
Version mismatch. 4.1.3 expected but only 3.6.0 supported

Not sure if some of my settings may have something to do with it, but i have no other addons installed.

**Comment by JMartinez9820** [comment]
This is not an issue, but rather a recent change. Project Brutality now requires GZDoom 4.1.3 to run. Please update if your computer can run GZDoom 4.1.3. If your computer can not handle GZDoom 4.1.3, try downloading a build of GZDoom Vintage. These first two builds here are the only Vintage builds to run PB currently. 
GZDoom Vintage builds can be found here: https://devbuilds.drdteam.org/gzdoom-vintage/

**Comment by JMartinez9820** [comment]
I meant update your GZDoom version to 4.1.3.

**Comment by webursey** [comment]
Yeah, I updated, and it's working now

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by scaryred24** [comment]
Please refrain from putting in promotions in your issue trackers please. You may not have noticed but when that gets shoehorned into your responses, it makes it look less professional and more into advertising a product. I edited your response to better reflect the issue tracker. 

Now with that aside I like to say that from here on out, you need GZDoom 4.1.3 in order to try out this mod. Make sure you are up to date before you report any bugs. This goes to every other report from here on out.
