### ISSUE TITLE
Lightning head and Demon Strenght issues

### ISSUE THREAD

**Issue by LastManonEarth6604** [pa1nki113r/Project_Brutality#216]
Two issues to report: 

1) When picking a demon strength rune, and doing some fatalities, specifically to a zombieman (not sure which one, only saw it had a helmet, and it was not the pyro zombie) doomguy got zombieman`s head in the hand flashing between punching hands and holding the head, like going to smash mode and will keep jumping between the head and the punching hands. 2) Also, for some reason a zombie has this light in the head, seems the lesser demon but without animations.

![Screenshot_Doom_20190820_104453](https://user-images.githubusercontent.com/53973921/63353233-d162aa80-c338-11e9-8aad-04bf2bbe406c.png)

using gzdoom 4.1.3 and the below load order

[Global.Autoload]
Project_Brutality-master-08-11.pk3 (latest release)
PB_newssgreloadupdated4-28-19.pk3
PB_Multiplayer_ForceClass_ProjectBrutality.pk3
brightmaps_plus.pk3
darkdoomz_v1.7.1.pk3
hxrtchud-pb3_gh762e2f1.pk3
R_Hud_Stuff_ZDoom_v1.pk3

[doom.id.doom2.commercial.Autoload]
SkyboxesD2.wad
doom2_titlemap.pk3
BDCME_DOOM+DOOM2.wad

**Comment by AlexThePianoNailer** [comment]
Man they're doing something with hitboxes right now so light in the head is deliberate.

**Comment by JMartinez9820** [comment]
@LastManonEarth6604 The lights on the head are the dynamic hitboxes for the Zombieman. Currently, the Zombieman's hitboxes are in an experimental phase, and the Zombieman overhaul is incomplete. That explains why the Zombieman is missing certain animations. The Demon Strength rune has been known since the public 2018 beta. This I believe was an issue for Brutal Doom as well. This should be taken care of at a later point in the Monster Overhaul and development. Thank you for reporting these.

**Comment by LastManonEarth6604** [comment]
Sure, will report whatever I feel is a bug, sorry if already reported or sorry if missing info. I always try to assist improving PB,  and to provide what I am using as add ons  and clues to help you guys. It`s  strange I did not remember that hitboxes was in mind, I was aware of that, not sure why I did not recall that.  Thanks.
