### ISSUE TITLE
GZDOOMBUILDER not showing project brutallty assests

### ISSUE THREAD

**Issue by Drjonesisanerd** [pa1nki113r/Project_Brutality#229]
Whenever I load project brutality in my gzdoombuilder resources, it never shows all it shows is the default doom assets but whenever it test it it loads pb. can you make it so I cloud to use the assets like level enchantment stuff and weapon upgrades and custom demons and more?
![image](https://user-images.githubusercontent.com/55871516/65749767-00043b80-e0c4-11e9-8604-1d45e51020a8.png)

**Comment by Drjonesisanerd** [comment]
![image](https://user-images.githubusercontent.com/55871516/65749881-4eb1d580-e0c4-11e9-9122-254c8a48017a.png)

**Comment by Drjonesisanerd** [comment]
![image](https://user-images.githubusercontent.com/55871516/65749889-596c6a80-e0c4-11e9-8d3a-cdde09c82613.png)

**Comment by tunbridgep** [comment]
Most of the enemies and weapons are designed to replace the vanilla Doom ones in your maps, they have special spawners etc for each of them. As a result, each of the enemies don't have doomednums associated with them, since they are only spawned through the randomiser, and as such they can't be placed in maps directly.

BUT I can see a case for making some of the more exotic enemies, weapons and items placeable through doomednums specifically. This is an issue that is going to crop up anyway if someone decides to add Skulltag support, as that will need a spawner specifically for the railgun and grenade launchers, which will mean they will be available in Doom Builder. The Doom Enhancement Script will never be available as it was just removed. Someone needs to extract it out of Brutal Doom and make it a separate mod.

**Comment by JMartinez9820** [comment]
Ultimate Doom Builder support is going to be added in the next version, so I'm going to close this for now.
