### ISSUE TITLE
Project Brutality Crashes

### ISSUE THREAD

**Issue by shinymewy** [pa1nki113r/Project_Brutality#252]
I was playing PB 3.0 when I landed in water trying to shoot and my game froze and crashed. Is there a way to explain it?

**Comment by JMartinez9820** [comment]
Is it okay if you post a screenshot of the issue you are having? If you can't, feel free to join the Project Brutality Discord server and post the screenshot on the bug reporting channel.
https://discord.gg/2hJxXPc

**Comment by shinymewy** [comment]
For some reason when I'm on the Project Brutality server, only one text channel pops up. idk why that happens and I have also restarted Discord and its not showing any other text channels.

**Comment by scaryred24** [comment]
You need to check your direct messages. A bot should have sent you a message so that you can verify that you are not a bot. Once you do that, you will see the remainder of the server. If you don't, I suggest that you check your Discord settings again making sure that you don't have direct messaging turned off and try again. This is especially important as the bot won't be able to tell if you passed the verification or not if someone is to manually bypass the system. Anyone who doesn't verify within 24 hours of joining will be automatically kicked.

**Comment by goldenmobster** [comment]
I checked and I fired nearly all the weapons underwater and it never crashed or froze on me, It looks like this issue has been resolved and therefore i am closing it
