### ISSUE TITLE
DMR grenade launcher upgrade

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#255]
This upgrade doesn't use up any ammo. I know its not a very useful upgrade. Just though I would mention it.

**Comment by goldenmobster** [comment]
Kinda does , It uses the Grenades

**Comment by TonyH1234** [comment]
When I was using it my grenades weren't running out.

**Comment by goldenmobster** [comment]
Can you post a video or gif of that please ?

**Comment by goldenmobster** [comment]
> When I was using it my grenades weren't running out.
You are right, when using the Grenades [Underbarrel GL] the grenades never run out, The Grenades only used when tossed/thrown [By Hand]

That is very odd and we will take a look at this when we can, Ty for reporting this

**Comment by JMartinez9820** [comment]
This is due to equipment inventory system breaking the system, the DMR weapon script even states this. Although I believe the DMR grenade launcher is being scrapped in the future in favor of a new upgrade candidate known as the HDMR (Heavy DMR). It will come with underbarrel grenade launcher as well.
