### ISSUE TITLE
Level enhancements no longer work.

### ISSUE THREAD

**Issue by Mechanical-sanity** [pa1nki113r/Project_Brutality#263]
I opened the game, but there was no level enhancements.

**Comment by Cacodemon345** [comment]
Level enhancements have been removed in light of the current push to abandon Brutal Doom assets completely at some point.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by RinMaru** [comment]
o will somthing similar come out of this in the futur?

**Comment by goldenmob72** [comment]
Probably an add-on, If Mark makes a MES add-on

**Comment by scaryred24** [comment]
That's if it ever happens. MES was removed because it was a very hacky way of "enhancing" a map. While it did it's job, it however did not do a very good job at running efficiently. Due to a lot of conflicts in the code mainly having it running in the background at all times expecting a map that looks like or similar enough to the vanilla iwad maps did put a strain on performance. Then again aside from like map of chaos it never really did anything for custom map packs so its omission was sadly overdue and was needed. It wasn't a choice that the devs wanted to make but it was for the better in the long run. Unless one day it could be added back in a form of an add-on or mutator, its sadly going to be absent from here on out.
