### ISSUE TITLE
Offending with fists selected doesn't work correctly

### ISSUE THREAD

**Issue by Epictyphlosion** [pa1nki113r/Project_Brutality#272]
In older versions of PB, if you pressed the "offend" button with your fists selected, both your hands would flip the bird. Now, only your right hand does it, and your fists disappear for the first few frames while you're flipping off whatever you're aiming at.

**Comment by JMartinez9820** [comment]
Minor oversight for the offending. Both fists flipping the bird may have broken due to the fist/weapon overhauls. Also, proper double offend sprites haven't been made yet. As for the second, I'm very unsure what causes that. Can you post a video so the team knows what causes the second problem? That would be very well appreciated.

**Comment by Epictyphlosion** [comment]
> As for the second, I'm very unsure what causes that.
Forgot to mention that they only disappear for the first few frames after you press the offend button, sorry about that. If you want, I can still make a video showing the bug and a comparison with an older release

**Comment by JMartinez9820** [comment]
@Epictyphlosion This issue is now fixed in the latest commit, feel free to close this issue.
