### ISSUE TITLE
sprite palette messed up with some monsters

### ISSUE THREAD

**Issue by ak1dd** [pa1nki113r/Project_Brutality#279]
With the most recent build I am getting weird palette issues with some of the monsters.  The Pain Elemental that I think spits the green flame lost souls looks awful.  Occasionally some of the zombie human characters too.   I've also seen a dead body that looks like it is glowing pink.    
![Screenshot_Doom_20191207_141931](https://user-images.githubusercontent.com/38289720/70381321-e28df200-18fc-11ea-91c4-b6fe365e791f.png)
I'm using GZDoom v.4.2.4 and various map wads

**Comment by JD531** [comment]
Have you already tried without the custom map? If the custom map includes a palette color that is not intended for mods, then is not a PB issue nor GZDoom issue. You may as well try loading the map first and then the mod and see if that can resolve the issue, otherwise, nothing that can be done about that. Also, providing the name of the wad that is being played is important too.

**Comment by ak1dd** [comment]
JD531 - you are right.  I could have sworn I tried it with other maps and saw the same... thanks for all you are doing.
