### ISSUE TITLE
Player's legs' color dont respect Player Profile actual color. The drawn sprite when looking down is always green

### ISSUE THREAD

**Issue by BlyatSlayer** [pa1nki113r/Project_Brutality#285]
Title

**Comment by JMartinez9820** [comment]
Not a top priority at this time, possibly even never due to the number of sprites the team would have to do. Because the sprites themselves were made like that, they will need to be modified to match the player's color. The kicking sprites themselves is around 138.

**Comment by Cacodemon345** [comment]
Plus, GZDoom lacks the ability to apply PSprite translations yet. There's a PR that I have made for GZDoom that adds it but I believe it's put on hold for now.

**Comment by JMartinez9820** [comment]
@BlyatSlayer The player legs now respect the player's color since the PSPF_PLAYERTRANSLATED flag has been implemented. Thank Cacodemon345 for that awesome feature. However, its currently in a buggy state and needs sprite updates to match with the marine's proper green color, and requires GZDoom 4.3.1 or higher. This issue can be closed for now.

**Comment by JMartinez9820** [comment]
This issue can be closed, the leg sprites now respect the player color since the pspf_playertranslated flag was added.
