### ISSUE TITLE
Some idea + 1 problem

### ISSUE THREAD

**Issue by raggamemas** [pa1nki113r/Project_Brutality#289]
Hello, just an idea:
- dont accept key "Use" from Player, then Player reloading gun (Player dont have 3rd hand)
- dont close door (opened, paused) when distance between more than or timer. You know IRda in future doors must be everywhere. Ofcourse if doors close\opes has standart behavior script
- Damaged standart white door (Explosing) (just littlebitslowly opens, sparks like a broken flashlight, and it all)
- Able to take full-parted zombie\imp corpse

And have some problem:
- If use WAD (mapOfChaos) on map04 you start on middle of level, and in start level you see another DoomGuy, if kill him - you die to. With previos realises it dont be like what.
- Another problem, but other issues already have it.

Thanx for hard work =)

**Comment by JMartinez9820** [comment]
The don't accept key use from player when reloading I think won't happen since I think its a limitation that the Doom engine can do, was there another mod that does that though? As for Maps of Chaos, I think that might be an issue with the map itself, idk. Suggestions don't really belong here, instead of here, suggestions should be posted in the [Discord](https://discord.gg/2hJxXPc) server instead, in the channel suggestions for pb. Make sure you have your DMs set to receive messages from other users, a bot will ask for verification in DMs.
