### ISSUE TITLE
AmmoFactor & reloading

### ISSUE THREAD

**Issue by nectocaris** [pa1nki113r/Project_Brutality#304]
I believe this is a Project Brutality-specific thing. When specifying an AmmoFactor <1 in ZMAPINFO (e.g. 0.5), this will cause all stored ammo to be depleted when the weapon is reloaded. Values >1 will reduce the amount drawn from stored ammo by 1/factor (I think) when reloading. No idea if it even affects ammo pickup - didn't get that far. - The same happens if such a value is set for DoubleAmmoFactor and the DoubleAmmo flag is enabled in options.

Possibly related, DropAmmoFactor seems to have no effect at all.

**Comment by secretagentjr** [comment]
this is because the magazine/thing your guns carry is actually classified as ammo, and ammofactor lowers or raises anything with ammo depending upon what you type in.  when you put ammofactor 0.5 you're effectively making the pistol magazine max 8, or the dmr magazine max 16, but when reloading, a check is made for the whatever the ammo is using, ex, dmr, it checks for 31 dmr magazine, and if it doesn't reach it, it keeps giving and taking the ammo type it uses until it reaches 0. but since the max is 16 with ammofactor 0.5, it will never reach it. hence draining all your ammo. this is not fixable unfortunately. the max is also technically raised if using ammofactor 2, but you won't ever reach anything higher than 31 due to the way reloading works.

**Comment by fgweller** [comment]
Huh. Crap. Seemed like a nice approach to make the game a little more challenging in a resource-management kind of way (as opposed to greater squishiness). Not to be then, I guess :/

**Comment by JMartinez9820** [comment]
This issue can be closed after nearly a year without a reply.
