### ISSUE TITLE
Monster Variants spawn randomly instead of changing with progress

### ISSUE THREAD

**Issue by Wadanny** [pa1nki113r/Project_Brutality#309]
Sorry if this is covered somewhere else.

I really liked in the earlier versions, how the different or harder monster variants gradually got introduced as the WAD progressed. This seemed like a really nice touch as it streamlined the game progression nicely and meant you could look forward to the tougher variants as you got a better armoury to fight them.

Now it seems that each monster spawns a random version of itself regardless of whether you're on an early or later level. Is this an intended new feature or something that will be fixed later on?

**Comment by JMartinez9820** [comment]
This is because of the spawn set currently set with PB, by default, it's at Randomized Progression. This can be changed in Global Settings, and then Spawn Preset configuration inside Project Brutality options. Here are what the spawn sets do.
* Tiered Progression - Harder variants of enemies spawn and weapon upgrades spawn depending on progression, mostly in harder levels up.
* Randomized Progression - Weapon upgrades and enemy variant spawns are at random, weapons upgrades are also a bit more common
* Brutal Doom (I think this should be renamed to Vanilla Doom in the feature), mostly just the weaker Tier 1 monsters, similar to Vanilla.
* Chaotic Random - Harder monster spawns are random and weapon upgrades are more common, can also potential have full use of the weapon arsenal.
* Death Wish - Even harder monster spawns, mainly Tier 3 or Tier 4 monsters, weapon upgrades also more common.

**Comment by Wadanny** [comment]
Brilliant, cheers!

**Comment by JMartinez9820** [comment]
I hope what I said helped. If so, this issue can now be closed.

**Comment by Wadanny** [comment]
It did thanks, I suppose all I would ask is what I should change it to to
emulate the gameplay of 2.03s version?

**Comment by JMartinez9820** [comment]
I'll be on the [Discord] (https://discord.gg/2hJxXPc) server if you need more help. (Click on the word "Discord" to access the server link)
