### ISSUE TITLE
many bugs

### ISSUE THREAD

**Issue by yeyeyeety** [pa1nki113r/Project_Brutality#332]
quick melee dosent show the hand, deagle and dual wielding with certain weapons use double the ammo, some enemies disappear upon death, mancubi and its variants disappear and die with one headshot, iron sights are way to low

**Comment by JMartinez9820** [comment]
The Github build does mention that it's not complete and has bugs. As for the Mancubus, the sprites are okay on my end. If you are referring to one of its variant, the Daedabus, that's due sprite conflicts, that has since been fixed though. As for quick melee, I don't know what you mean but some weapons don't have proper sprites for them. Deagle and Revolver using double ammo I think is intentional, and since dual wield is tied to one script it only shows the ammo for one pistol. As for the iron sights, not a top priority currently, we are aware of that but sometimes getting iron sights aligned with the cursor properly can be hard. Brutal Doom has this issue as well. Can you please better elaborate on your description, so the devs can take a look at it? Thanks for the report.

**Comment by AREVAL00** [comment]
demon variants have a lot of sprite problems, for example, the Infernus shows like a Baron Of Hell when killed by nails/flechettes

**Comment by JMartinez9820** [comment]
Those are just placeholders for now. Some enemies have placeholder sprites until they get proper sprites.

**Comment by yeyeyeety** [comment]
my bad i was using an older version im using the newer one now and pretty much all the problems are fixed

**Comment by goldenmobster** [comment]
Then. in that case i'm closing the issue
If you DO get those or one of em Bugs feel free to re-open the issue
