### ISSUE TITLE
Hitscanners need to be nerfed

### ISSUE THREAD

**Issue by fctorial** [pa1nki113r/Project_Brutality#346]
Hitscanners are too OP in project brutality. Main reason is that they have instant aim.

An aim direction could be assigned to gunners and they will have to move it towards the player at a certain speed (which might depend on skill level).

**Comment by JMartinez9820** [comment]
I don't think there are any hitscan based enemies in Project Brutality, I believe all enemies including the Zombies, Sergeants, and Commandos are projectile-based. Also, in my opinion, this sounds more like a suggestion rather than a bug, I recommend posting this as a suggestion on the Project Brutality Discord server if you are in it.

**Comment by scaryred24** [comment]
There are no hit scanners at this current status of development. Thread closed.
