### ISSUE TITLE
shotgun reload and BDv21 weapon sprites and traditional weapon sprites.

### ISSUE THREAD

**Issue by Mechanical-sanity** [pa1nki113r/Project_Brutality#35]
Someone already mentioned the shotgun reload problem. but basically, when you reload, the shotgun throws away all shells. this is a bit personal preference, but for the BDv21 mode, can you just put the original sprites from BDv21? I really don't like the new sprites for BDv21 mode. and another thing is the traditional mode sprites. I also don't like the sprites for that either due to it not feeling like the original doom sprites. can you simply just use the purist mode weapon sprites from BDv21?

**Comment by JMartinez9820** [comment]
I don't think that's going to happen. The BDv21 sprites could be an addon for the v21 mode

**Comment by scaryred24** [comment]
Due to some issues in the past with the creator of Brutal Doom v21, we are trying to stray away from using his assets as much as possible. There are unnoficial addons that will adresss this as the community may need to make said conent but as of right now, we have zero plans to implement the shotgun from v21.

**Comment by Mechanical-sanity** [comment]
can you at least tell me some of those addons?

**Comment by JMartinez9820** [comment]
This issue can be closed as the BDv21 class was scrapped
