### ISSUE TITLE
Dash Effect

### ISSUE THREAD

**Issue by Mr-Blazkowicz** [pa1nki113r/Project_Brutality#379]
just a minor issue.

If you dash then instantly climb a surface, the dash effect will be in loop(those white spikes in the corners of the screen) and if you move to the sides, the camera will move more inclined.

**Comment by JMartinez9820** [comment]
This is due to how the dash effect working when it air. When you press dash, the dash effect will still keep going until you land on the floor. Unfortunately I don't how this can be fixed, the current only way is to disable the dash effect in the Visual Settings in the Project Brutality Settings. Very minor and not really a thing to fix right now.

**Comment by Mr-Blazkowicz** [comment]
Also i noticed a very small detail, when you are falling and if you jump in mid air(double jump) there's a semi-kind of tiny jump effect after that, is like you step on a surface for a millisecond.

**Comment by JMartinez9820** [comment]
> Also i noticed a very small detail, when you are falling and if you jump in mid air(double jump) there's a semi-kind of tiny jump effect after that, is like you step on a surface for a millisecond.

Sorry for the late reply but this happens on the original ZMovement 3.0 as well. I'll take a look at it too see if I can do something about it.
