### ISSUE TITLE
Crashes soon after I start game

### ISSUE THREAD

**Issue by GunMummy** [pa1nki113r/Project_Brutality#471]
I've been experiencing random crashes in the latest version. I don't know if this is because it's new and a WIP, but I thought I'd post anyway.

It runs fine for about a minute, then crashes. I have the report

[CrashReport.zip](https://github.com/pa1nki113r/Project_Brutality/files/5103331/CrashReport.zip)

**Comment by JMartinez9820** [comment]
Which GZDoom version are you using, and what are your PC specs?

**Comment by GunMummy** [comment]
Latest GZDoom (v4.4.2).

Win10
Intel Core i5-6600 CPU@3.30Hz 3.30GHz
RAM: 16.0 GB
Storage: 1TB
GPU: GeForce GTX 970 (driver's up to date)

No overclocking

**Comment by JMartinez9820** [comment]
@GunMummy Late response but try using GZDoom 4.3.3 or LZDoom 3.86. The latest GZDoom versions are crap and have a lot of problems such as memory leaks.

**Comment by d64d64** [comment]
My game also crashed every time basically seconds after I started shooting someone. Downgrading to GZDoom 4.3.3 did solve the issue. Regular Brutal Doom works also with 4.4.2.

**Comment by JMartinez9820** [comment]
I do have one thing to say before anyone downgrades to 4.3.3. Just remember that compatibility with certain GZDoom version are subjected to change if the team decides to use newer features from later versions of GZDoom. I hope GZDoom 4.5 fixes a lot of the problems that 4.4.x had. Otherwise LZDoom is another good alternative.
