### ISSUE TITLE
HRRDY is not being reproduced?

### ISSUE THREAD

**Issue by DR0L43R** [pa1nki113r/Project_Brutality#527]
The sound "HRRDY" (from /SOUNDS/COMBAT/WEAPONS/Demon Tech/) is not being reproduced when the referred weapon is selected. 

Also, current sound file is much low. The ealier file from version 1-21-18 is much better :-D

**Comment by JMartinez9820** [comment]
@DR0L43R This is because there is no A_PlaySoundEx/A_PlaySound/A_StartSound coded in the SelectAnimation state when being selected. The code for the Demon Tech Rifle is found in actors/weapons/Slot9. If you want to fix this on your own, you can add this piece of code in the SelectAnimation state of the Demon Tech Rifle. 
> TNT1 A 0 A_StartSound("HRReady")

**Comment by JMartinez9820** [comment]
Like this for example.
> SelectAnimation:
			TNT1 A 0 A_StartSound("HRReady")
			TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady")
			TNT1 A 0 A_JumpIfInventory("FireModeAcidGun",1,"SelectAnimation2")
			D2T0 ABCDE 1

**Comment by DR0L43R** [comment]
I will test this in my local file. Thanks for advice.

**Comment by DR0L43R** [comment]
> 
> 
> Like this for a completed example.
> 
> > SelectAnimation:
> > TNT1 A 0 A_StartSound("HRReady")
> > TNT1 A 0 A_JumpIfInventory("GoFatality", 1, "Steady")
> > TNT1 A 0 A_JumpIfInventory("FireModeAcidGun",1,"SelectAnimation2")
> > D2T0 ABCDE 1

It worked fine for me. I don't have permissions to edit the source here. 

I just couldn't change the sound file. If our colleagues are able and get a better sound file, I prefer to leave it up to you.
