### ISSUE TITLE
If Precache GL Textures is on, loading times take forever after dying.

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#533]
I turn Precache GL textures on as this removes most of the stuttering issues when loading a new map. However after dying I am forced to exit GZDoom, restart and then reload my game otherwise loading times are ridiculous. This does not happen If I reload without dying.

**Comment by JMartinez9820** [comment]
This issue is known and is exactly why I never turn on Precache GL Textures. Does this issue persist with other mods too (Brutal Doom, Final Doomer, Complex Doom, etc.)?

**Comment by JMartinez9820** [comment]
Update: I just found some info regarding Precache GL Textures. According to Graf Zahl himself, Precache GL Textures only prevents delays due to uncached textures during gameplay. However if there are missing textures the game will stall for a short period of time to create those textures. My suggestion is to turn off Precache GL Textures for now. Otherwise, take a look [here] (https://forum.zdoom.org/viewtopic.php?f=4&t=39952) for more information.

**Comment by popguy12** [comment]
Precache GL should only be used with high res texture packs
it also runs whenever a save is loaded or a map is loaded
