### ISSUE TITLE
how can i increase blood and gore level?

### ISSUE THREAD

**Issue by zielony12** [pa1nki113r/Project_Brutality#563]
Hey, i want to have more blood than 255, in brutaldoom i can set it to 1k, but project brutality is better! Any command? Or should i change value of variable in project brutality's code??

**Comment by D3X1KAXYZ** [comment]
PB has switched from the brutal gore system to the nashgore system. This is in order to improve performance. You could try changing the variables via the console, however there may be side effects to doing so. best case scenario, it works fine. worst case scenario, the game crashes.
the variable responsible for this is `nashgore_bloodamount`
related variables are:
`nashgore_maxgore`
`nashgore_gibamount`
Another possible solution that may work is to load up another gore mod.
I personally don't know what gore mods work with pb 3.0, though.

**Comment by goldenmob72** [comment]
This not an issue,Therefore, It shall be closed.
