### ISSUE TITLE
Problem with Jumping While in Acid

### ISSUE THREAD

**Issue by GeoDash897** [pa1nki113r/Project_Brutality#568]
Hello!
When in acid, it difficult for the player to jump. This makes it very annoying when falling into it on accident or falling into it in order to get a secret (like the **Berserk secret** on the outside bridge area of *Map 2* and the **Megaarmor secret** bathroom area of *Map 6* of Extermination Day).

![PB Jumping Acid Bug](https://user-images.githubusercontent.com/55932902/101825981-5fe5d700-3afc-11eb-9078-5d99757efe85.gif)

*Sorry for low quality gif- I needed to make the file size smaller to be able to post it on here.*

This happens on the most current master branch version of Project Brutality (last commit = **11/30/20**) on **GZDoom 4.5**.

Sometimes I am able to jump out of the acid by mashing double jump and kick, but I feel that this happens **randomly**.
Is this supposed to occur?

(I know that in the original Doom games, you would have to kill yourself if you fell into a pit of acid- is this something similar to that)?

**Comment by JMartinez9820** [comment]
> Sometimes I am able to jump out of the acid by mashing double jump and kick, but I feel that this happens randomly.
Is this supposed to occur? (I know that in the original Doom games, you would have to kill yourself if you fell into a pit of acid- is this something similar to that)?

@GeoDash897 
Correct. Not being able to jump out of a hazard floor is intentional for vanilla Doom based maps. There is an option located in the Gameplay options in the Project Brutality settings called "Hazards prevent advanced movement". Turning it on enables the player to jump or dash in hazard floors, or you can also type pb_hazardmovement 1 in the console

**Comment by GeoDash897** [comment]
Should I close this issue then since it was just my settings that caused the problem?

**Comment by JMartinez9820** [comment]
If what I said fixed your problem, then yes.

**Comment by GeoDash897** [comment]
It was the option, I had it set to false. Thanks for the help.
