### ISSUE TITLE
Kick hotkey does nothing?

### ISSUE THREAD

**Issue by Rowsol** [pa1nki113r/Project_Brutality#606]
I may be a moron but I just downloaded this and I can't kick at all. I assigned a key to it and nothing.

**Comment by JMartinez9820** [comment]
@Rowsol Kick key is mapped in Customize Controls under the Project Brutality keys. Just map it to Q. Another suggestion I would try to map with Brutal Doom, as some of the keys from BD are carried to PB. Otherwise, you may have to do a reinstall of GZDoom (basically deleting everything) if it doesn't work/

**Comment by goldenmob72** [comment]
It works for me just fine, it's your GZDoom Ini or the controls
for now this will be closed
