### ISSUE TITLE
Dash Effect bugs + extra

### ISSUE THREAD

**Issue by Mr-Blazkowicz** [pa1nki113r/Project_Brutality#612]
Hi guys, i recently found 3 bugs on the latest build (21/01/21), the dash effect looks weird when dashing to every side, also the dash keeps when you dash and after that, do a ledge grab, if you dash after this, the effect will dissapear, also there's a *kinda third leg bug* when you do a kick jump looking down.

-Tested on GZDoom 4.5.0 x64 with and without mods on ZDL

https://youtu.be/qBAefe2EOVo

https://youtu.be/0gRB4jBo5Y0

https://youtu.be/19mZqpHKFn0

**Comment by JMartinez9820** [comment]
The dash overlay looking bugged is new because of recently changed code. Disabling it is the only way for fixing it for now. The dash overlay not disappearing is something I've tried to look into, but failed. It disappears when you land on the floor. About that kinda third leg bug, i couldn't really see it even with using i_timescale. I think it's because of that the leg overlay code with changed to make the right leg disappear when you kick.

**Comment by tunbridgep** [comment]
What helmet mod is that?

**Comment by goldenmob72** [comment]
CatsVisor HUD

**Comment by popguy12** [comment]
as far as i know this whole issue is fixed now i think, if it shows up again or still persists feel free to reopen
