### ISSUE TITLE
Mysterious lag issues relating to update

### ISSUE THREAD

**Issue by Siegfried1337** [pa1nki113r/Project_Brutality#654]
There seems to be an massive frame drop when there are a huge amount of monsters involved. Previous versions didn't have this issue. Any idea what's causing this?

**Comment by JMartinez9820** [comment]
I'm not entirely sure, but it could possibly be the effects graphics. Final Dragon removed the backgrounds to fix an issue with the Night Vision. Although transparency is slightly more graphic intensive than solids. If you have your PC specs please post them here. Otherwise, this is not a top priority.

**Comment by JMartinez9820** [comment]
Also, did you try using Final Dragon's edited GZDoom ini files

**Comment by Siegfried1337** [comment]
Yes

**Comment by Siegfried1337** [comment]
New update seems to have fixed lag issue
