### ISSUE TITLE
[Question] Will there be any plans to make this an official doom dlc or any plans to port this on ios?

### ISSUE THREAD

**Issue by Darthveder69420** [pa1nki113r/Project_Brutality#673]
Just had some questions on this really good mod.

**Comment by JMartinez9820** [comment]
This issue is instantly invalid. It would be impossible to make it DLC due to advanced coding, and it's way too powerful to run on that port. As for iOS, there is no way to play GZDoom mods on iOS. If you have an Android, you can use Delta Touch. I did hear that Beloko Games, the developer of Delta Touch, plans to make an iOS version of Delta Touch after he finishes the Android port. Apple is very restrictive when it comes to third-party applications.

**Comment by Darthveder69420** [comment]
Ah well gonna be using android for now. Also Even if apple won’t allow to put delta touch on appstore, it will be possible to download an ipa from them and then installing and signing it using alt store, Reprovision etc. Do you have a link to any of their social like Reddit or twitter?
