### ISSUE TITLE
Upgraded plasma gun dual wield resets and upgraded UAC41 rifle does hold ADS not working

### ISSUE THREAD

**Issue by sebastianpanetta** [pa1nki113r/Project_Brutality#720]
Found this two bugs:

- Upgraded plasma gun: when dual wield and then switched, it resets to single wield, also noticed the ammo bar is still one (should be two)
- Upgraded UAC41 rifle: ADS for toggle and hold modes only results in a toggle behavior

**Comment by JMartinez9820** [comment]
@sebastianpanetta 
1. I see no issues with the upgraded plasma rifle, however it's very outdated and still has the old dual wield system and two script system of previous builds. Intentional for now until it's overhaul or it gets changed.
2. Do you have a video demonstrating this? I see no issues with it on my end

**Comment by JMartinez9820** [comment]
Edit: I feel like an idiot. The LMG is not overhauled yet, this will be fixed on the overhaul. Although it will take a while so I may put the new upgraded system in place on my branch for now.

**Comment by sebastianpanetta** [comment]
Thank you very much for the info!
