### ISSUE TITLE
Pulse Cannon issue with killing minigun commandos plus pinky rework

### ISSUE THREAD

**Issue by NewAgeKid52** [pa1nki113r/Project_Brutality#732]
If the minigun guys get killed with a pulse cannon, they disappear but they do not drop their minigun behind. I think I also tried killing them with the plasma rifle as well and the minigun guys also do not drop their minigun on the ground after they die. Meanwhile killing most other enemies with the pulse cannon makes them drop their weapon or a demon energy ball as they should.

The pinkies (demon guys with only a melee attack) I feel need a rework. They do really pitiful damage to the player compared to everyone one else and even imps typically kill the player much faster and easier in melee range than pinkies do. Even the top tier black one-eyed pinky isn't much of a threat at all compared to zombiemen or imps. Since they don't have any ranged attacks, I feel they need a rework to make them do more damage faster with their only melee attack otherwise they are just pushovers.

Just a suggestion. Is it possible if one day a reload/switch ammo action can be cancelled near-instantly by switching to a new weapon? I think a soldier in real life if they were let's say busy trying to reload their rifle but an enemy came up while reloading they'd drop their rifle and pull out their pistol and fire a shot, rather than continue reloading their rifle and let the enemy shoot them.

**Comment by popguy12** [comment]
its known that theres a few cases where enemies are weirdly enough dropping no weapons, or sometimes two weapons, its all gotta do with the deaths system

pinkies are gonna be overhauled at some point, probably next on the list after imps.

reload cancellation would be possible, but i think it would be better to find a different way of doing it instead of spamming A_WeaponReady everywhere, however, i think theres ideas still floatin around to be able to kick at all times
