### ISSUE TITLE
Dual SSG Freezing the game and LMG wrong ammo counting

### ISSUE THREAD

**Issue by Nightmarekiller84** [pa1nki113r/Project_Brutality#800]
I discovered that when you wielding Dual Super Shotguns and you are out of ammo(clip and reserve) and continue to press the primary or secondary fire the game will freeze

The UAC LMG when you reload the 1st time only, it will remove exactly 75 bullets, this happens only when your ammo reserve is full
For example if my ammo in reserve is 600 and I reload the weapon 1st time it will remove 75 bullets exactly regardless how many I shoot from the weapon's clip. Afterwards it will count properly.

**Comment by JMartinez9820** [comment]
The SSG I'll try to investigate a possible fix for it just like I did with the Revolver and Deagle.
As for the LMG, that's actually intentional for it to do that when ikdfa told me. It's for the mode swap and he wanted to be as universal it can be. But if someone does report it again then I made possibly make a change to it so it matches with other weapons.

**Comment by Nightmarekiller84** [comment]
Thanks for the info and help.

**Comment by Nightmarekiller84** [comment]
Ah I get it, but then again is weird. If it was because of changing mod it makes perfect sense BUT everything I told you was WITHOUT changing the bullets from normal to micro missiles.

**Comment by Nightmarekiller84** [comment]
I noticed that you fixed the SSG.  I download it from here ?

**Comment by JMartinez9820** [comment]
https://github.com/JMartinez9820/Project_Brutality/tree/JMartinezBranch

**Comment by Nightmarekiller84** [comment]
Thanks for your hard work
