### ISSUE TITLE
Hell Warrior

### ISSUE THREAD

**Issue by Ganbare-Lucifer** [pa1nki113r/Project_Brutality#804]
Are you open for new monsters submissions?

I have made the Hell Warrior edited from the Cyber Paladin with the additional gore and gibs. I'm waiting for any answer as possible.

**Comment by JMartinez9820** [comment]
@Ganbare-Lucifer I would recommend asking Mryayayify (aka MickeeYoofers), Keeper, or HylianJuggalo about this, in fact asking HylianJuggalo would be best because he has plans for monsters or new monsters for PB. We also plan of writing all monsters, including new monsters, to ZScript code, so if you want to consider helping, you can try to play around with ZScript if you like.

**Comment by Ganbare-Lucifer** [comment]
> 

Neat, so do I start putting the code and the sprites in the master thing?

**Comment by JMartinez9820** [comment]
Not yet, if you're on the Discord server, feel free to ask HylianJuggalo regarding monsters. You can also ask Keeper and Mryayayify too since they also do work related to the monsters

**Comment by JMartinez9820** [comment]
Going to close this issue issue. Something like this can be on the Discord rather than here.
