### ISSUE TITLE
Ridiculously fast demons

### ISSUE THREAD

**Issue by TonyH1234** [pa1nki113r/Project_Brutality#810]
Sometimes, not always, demons run at super speed, Even if fast monsters is off. I sometimes turn fast monsters on when I want a challenge and then turn it off if it gets too tough. Could this be what's causing it? The other monsters behave normally.

**Comment by JMartinez9820** [comment]
Idk what's causing this, but what I know is that I intentionally increased the FastSpeed of all Pinky Demon types to make them more faithful to their vanilla counterparts. Looks like I may have to decrease it a bit now because some of the demon scripts did warn that demons would move at Sanic fast speed if it used the default speed.

**Comment by JMartinez9820** [comment]
@TonyH1234 One more thing, you may need to start a new game or finish a level in order for certain changes to take effect, which I believe fast monsters is one of them.
