### ISSUE TITLE
Issue with certain levels of Speed of Doom, Scythe 2

### ISSUE THREAD

**Issue by JordanL2** [pa1nki113r/Project_Brutality#966]
I've had an issue using this mod with certain levels of Speed of Doom and Scythe 2 megawads. Specifically these levels:

[Scythe 2](https://doomwiki.org/wiki/Scythe_2): Any end of episode level (eg 5, 10 etc)
[Speed of Doom](https://doomwiki.org/wiki/Speed_of_Doom): Map 11 (presumably map 20 will also have this issue...)

What these levels have in common is:
1. There is a Romero Head
2. The level ends with a forced suicide

The problem I've encountered is a few seconds after the level starting, I hear the Romero Head death sound, and the level ends soon afterwards.

I'm using GZDoom with the latest master of Project Brutality 3.0, and no other WADs except the levels megawad. I've tried changing the order of the PB3.0 and megawad in gzdoom.ini, didn't fix it.

**Comment by JMartinez9820** [comment]
@JordanL2 
This is likely due to Voodoo Dolls and how weirdly barrels work. In future I'm going to be making an option that replaces the current barrels with the original vanilla Doom barrels because people have been reporting similar issues too, or trying to get a custom script that detects voodoo dolls

**Comment by JMartinez9820** [comment]
@JordanL2 
It turns out that I was completely wrong this whole time. A user in ModDB named mrPron just told me why this was happening, it was the BrutalTeleportDest actor causing it. I throws unnecessary A_Explode functions that hurt the Icon, causing premature death. I have now fixed this on my branch, so check it out. I'm very sorry for incorrectly explaining it, that was completely my fault. In fact most of the stuff is my fault.

**Comment by JMartinez9820** [comment]
Here is my branch:
https://github.com/pa1nki113r/Project_Brutality/tree/JMartinez-OfficialBranch

**Comment by JMartinez9820** [comment]
Edit:
I have made the decision to restore BrutalTeleportDest, although the big difference is that an inherited copy of the Icon of Sin is now in place to prevent the TeleportRemover damagetype from damaging it. This is was done due to issues with corpses blocking linedefs.
